'use client';
import { motion, Variants } from "framer-motion";
import { 
  ArrowLeft, 
  Target, 
  Eye, 
  Compass, 
  Code2, 
  Sparkles, 
  Layers, 
  Cpu, 
  ShieldCheck, 
  Zap, 
  HelpCircle,
  Plus,
  ArrowUpRight
} from "lucide-react";
import Link from "next/link";

// Visible structural rings mimicking the note canvas anchors
const SpiralSVG = ({ className }: { className?: string }) => (
  <svg className={className} viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="100" cy="100" r="90" stroke="currentColor" strokeWidth="1.2" strokeDasharray="6 6" className="opacity-40" />
    <circle cx="100" cy="100" r="65" stroke="currentColor" strokeWidth="1.2" strokeDasharray="4 6" className="opacity-30" />
    <circle cx="100" cy="100" r="40" stroke="currentColor" strokeWidth="1" strokeDasharray="2 4" className="opacity-20" />
  </svg>
);

// Explicitly typed animation variants to guarantee zero TS compilation failures
const fadeInUpVariants: Variants = {
  hidden: { opacity: 0, y: 30 },
  visible: { 
    opacity: 1, 
    y: 0, 
    transition: { duration: 0.6, ease: "easeOut" } 
  }
};

const staggerContainer: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.15 }
  }
};

export default function AboutPage() {
  const corePillars = [
    {
      icon: Target,
      step: "01",
      title: "Our Mission",
      description: "To build high-fidelity, cognitive workspaces that run entirely client-side—giving thinkers the ultimate tool for thought without sacrificing personal data privacy.",
      tag: "THE BASELINE",
      accentColor: "text-[#10B981]",
      bgColor: "bg-[#10B981]/5"
    },
    {
      icon: Eye,
      step: "02",
      title: "Our Vision",
      description: "A digital landscape where software respects absolute individual sovereignty. No mandatory account walls, no hidden cloud tracking, just pure execution on local silicon.",
      tag: "THE SOVEREIGNTY",
      accentColor: "text-[#F59E0B]",
      bgColor: "bg-[#F59E0B]/5"
    },
    {
      icon: Compass,
      step: "03",
      title: "Our Philosophy",
      description: "Local-First isn't an experimental feature or a toggle button; it is our foundation. If data is generated by your mind, it belongs safely inside your system files.",
      tag: "THE RUNTIME",
      accentColor: "text-[#EF4444]",
      bgColor: "bg-[#EF4444]/5"
    }
  ];

  const modularFeatures = [
    {
      icon: Layers,
      title: "Active Recall Modules",
      desc: "Turn raw markdown structures into modular study flashcards instantaneously. Run weight retention loops without pinging a remote server thread.",
      badge: "Local Spaced Repetition"
    },
    {
      icon: Cpu,
      title: "Isolated Local Threading",
      desc: "Canvas pipelines, block renderers, layout trees, and relationship map indexers calculate completely on your native device processes.",
      badge: "Pure Silicon Performance"
    },
    {
      icon: ShieldCheck,
      title: "Zero Operational Telemetry",
      desc: "We don't collect behavioral keys, index text files, or keep diagnostic track signatures. What you write remains perfectly invisible to our systems.",
      badge: "Absolute Privacy"
    },
    {
      icon: Zap,
      title: "Sub-Millisecond Loop",
      desc: "Eliminate API handshakes entirely. Text editing states update immediately to eliminate the input-lag present in common cloud sync apps.",
      badge: "Zero Network Lag"
    }
  ];

  return (
    <div className="min-h-screen bg-[#FAFDFB] text-[#1E293B] antialiased selection:bg-[#10B981]/10 relative overflow-x-hidden">
      
      {/* ──────────────────────────────────────────────────────── */}
      {/* GEOMETRIC LAYOUT DECORATIVE MATRIX                       */}
      {/* ──────────────────────────────────────────────────────── */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
        <SpiralSVG className="absolute -left-16 -top-16 h-64 w-64 text-[#10B981]" />
        <SpiralSVG className="absolute -right-20 top-24 h-80 w-80 text-[#F59E0B]" />
        <SpiralSVG className="absolute left-[15%] top-[45%] h-72 w-72 text-slate-200" />
        <SpiralSVG className="absolute -right-20 top-[60%] h-125 w-125 text-slate-300/60" />
        <SpiralSVG className="absolute -left-20 bottom-12 h-80 w-80 text-[#10B981]" />

        {/* Minimal alignment micro-dots copied from the layout references */}
        <div className="absolute left-[8%] top-[25%] h-2.5 w-2.5 rounded-full bg-[#10B981]/40" />
        <div className="absolute right-[12%] top-[15%] h-2 w-2 rounded-full bg-[#F59E0B]/50" />
        <div className="absolute right-[5%] top-[72%] h-3 w-3 rounded-full bg-slate-200" />
      </div>

      <div className="relative z-10">
        
        {/* ──────────────────────────────────────────────────────── */}
        {/* PREMIUM HEADER HERO SECTION                              */}
        {/* ──────────────────────────────────────────────────────── */}
        <header className="px-4 pt-16 pb-12 sm:px-6 sm:pt-24 lg:px-8 max-w-6xl mx-auto">
          <div className="flex flex-col items-center text-center">
            
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4 }}
              className="mb-6"
            >
              <Link href="/" className="group inline-flex items-center gap-2 rounded-full bg-white px-4 py-1.5 border border-slate-200/70 text-xs font-semibold text-slate-500 hover:text-slate-800 hover:border-slate-300/90 transition-all duration-150 shadow-xs">
                <ArrowLeft className="h-3.5 w-3.5 transition-transform group-hover:-translate-x-0.5" />
                Back to local environment
              </Link>
            </motion.div>

            {/* Clean metadata flag badge */}
            <motion.div
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="inline-flex items-center rounded-full bg-[#10B981]/10 px-3.5 py-1 text-xs font-semibold text-[#047857] border border-[#10B981]/20 tracking-wide uppercase"
            >
              PROJECT CORE &amp; STANDARDS
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.55, delay: 0.2 }}
              className="mt-6 text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight text-slate-900 max-w-3xl leading-[1.12]"
            >
              An Independent Lab Building the{" "}
              <span className="relative inline-block whitespace-nowrap">
                <span className="relative z-10 text-slate-900">Next Workspace</span>
                <motion.span
                  initial={{ scaleX: 0 }}
                  animate={{ scaleX: 1 }}
                  transition={{ duration: 0.65, delay: 0.7, ease: "easeOut" }}
                  className="absolute left-0 bottom-1.5 h-2.5 w-full bg-[#F59E0B]/25 -z-10 rounded-xs origin-left"
                />
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.55, delay: 0.35 }}
              className="mt-6 text-base sm:text-lg text-slate-500 max-w-xl mx-auto font-medium leading-relaxed"
            >
              Ploopus is designed cleanly on the edge—shielding your data structures from mandatory user cloud accounts.
            </motion.p>
          </div>
        </header>

        {/* ──────────────────────────────────────────────────────── */}
        {/* PREMIUM THREE-COLUMN STEPS (Asymmetry Design Layout)     */}
        {/* ──────────────────────────────────────────────────────── */}
        <section className="bg-[#F4F9F6] border-y border-slate-200/50 px-4 py-16 sm:px-6 lg:px-8">
          <div className="max-w-6xl mx-auto">
            <motion.div 
              variants={staggerContainer}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-80px" }}
              className="grid lg:grid-cols-3 gap-8"
            >
              {corePillars.map((pillar) => (
                <motion.div
                  key={pillar.title}
                  variants={fadeInUpVariants}
                  className={`group bg-white rounded-2xl border border-slate-200/80 p-6 transition-all duration-300 shadow-xs hover:shadow-md hover:border-slate-300 flex flex-col justify-between`}
                >
                  <div>
                    <div className="flex items-center justify-between border-b border-slate-100 pb-4 mb-5">
                      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                        {pillar.tag}
                      </span>
                      <span className={`text-sm font-mono font-bold ${pillar.accentColor}`}>
                        // {pillar.step}
                      </span>
                    </div>

                    <div className={`flex h-11 w-11 items-center justify-center rounded-xl border border-slate-100 mb-4 ${pillar.bgColor}`}>
                      <pillar.icon className={`h-5 w-5 ${pillar.accentColor}`} />
                    </div>

                    <h3 className="text-xl font-bold text-slate-900 tracking-tight mb-2">
                      {pillar.title}
                    </h3>
                  </div>
                  <p className="text-slate-500 text-sm leading-relaxed mt-1">
                    {pillar.description}
                  </p>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        {/* ──────────────────────────────────────────────────────── */}
        {/* MANIFESTO NARRATIVE (Clean Text Blocks)                  */}
        {/* ──────────────────────────────────────────────────────── */}
        <section className="px-4 py-24 sm:px-6 lg:px-8 max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
            className="space-y-12"
          >
            <div className="space-y-3">
              <div className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#10B981]">
                <Code2 className="h-4 w-4" />
                Origin Manifesto
              </div>
              <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight max-w-2xl leading-tight">
                We believe your software tools should be as rapid as raw thought loops.
              </h2>
            </div>

            <div className="text-slate-600 text-base sm:text-lg leading-relaxed space-y-6 font-normal">
              <p>
                Ploopus didn't emerge out of corporate strategy brainstorms or complex monetization blueprints. It was built because we got tired of running basic thought tracking apps that require stable network handshakes just to render raw markdown block strings.
              </p>
              <p>
                We realized that modern software tools had compromised something foundational: speed and privacy. When your workspace processes data in external databases, your ideas move slower than your processing power can allow.
              </p>
              
              {/* Premium Highlight Bar Callout Block */}
              <div className="border-l-4 bg-white rounded-r-2xl border border-slate-200/80 p-6 my-8 shadow-xs relative overflow-hidden">
                <div className="absolute right-3 top-3 opacity-5 text-slate-900">
                  <Sparkles className="h-12 w-12" />
                </div>
                <p className="font-semibold text-slate-800 m-0 text-sm sm:text-base leading-relaxed">
                  We operate with zero outside institutional investor oversight. This clean structural independence guarantees that product design stays strictly loyal to raw technical utility and data safety.
                </p>
              </div>

              <p>
                By engineering complex blocks—including interactive flashcard active study tools, board pipelines, and node networks—directly within browser-native system runtimes, your work remains fully portable. You own the files. You own the code environment. You control your workspace runtime.
              </p>
            </div>
          </motion.div>
        </section>

        {/* ──────────────────────────────────────────────────────── */}
        {/* PREMIUM MODULAR FEATURE DASHBOARD LABELS                 */}
        {/* ──────────────────────────────────────────────────────── */}
        <section className="bg-[#F4F9F6] border-y border-slate-200/50 px-4 py-20 sm:px-6 lg:px-8">
          <div className="max-w-5xl mx-auto">
            <div className="space-y-3 mb-16 text-center sm:text-left">
              <div className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-amber-600">
                <Sparkles className="h-3.5 w-3.5" />
                THE LOCAL STACK
              </div>
              <h2 className="text-3xl font-bold text-slate-900 tracking-tight">
                Architectural Features Built for Privacy
              </h2>
            </div>

            <motion.div 
              variants={staggerContainer}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-100px" }}
              className="grid sm:grid-cols-2 gap-6"
            >
              {modularFeatures.map((item) => (
                <motion.div 
                  key={item.title} 
                  variants={fadeInUpVariants}
                  whileHover={{ y: -3 }}
                  className="bg-white border border-slate-200/80 p-6 rounded-2xl shadow-xs hover:shadow-sm transition-all duration-150 flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <div className="p-2.5 rounded-xl bg-[#10B981]/5 border border-[#10B981]/10 text-[#047857]">
                        <item.icon className="h-4 w-4" />
                      </div>
                      <span className="text-[10px] font-mono font-semibold bg-slate-50 border border-slate-100 text-slate-400 px-2 py-0.5 rounded-md">
                        {item.badge}
                      </span>
                    </div>
                    <h4 className="font-bold text-slate-900 tracking-tight text-base mb-2">{item.title}</h4>
                  </div>
                  <p className="text-sm text-slate-500 leading-relaxed">{item.desc}</p>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        {/* ──────────────────────────────────────────────────────── */}
        {/* TRANSPARENCY ACCORDION STYLES                            */}
        {/* ──────────────────────────────────────────────────────── */}
        <section className="px-4 py-24 sm:px-6 lg:px-8 max-w-4xl mx-auto">
          <div className="space-y-3 mb-14 text-center sm:text-left">
            <div className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#10B981]">
              <HelpCircle className="h-3.5 w-3.5" />
              SYSTEM TRANSPARENCY
            </div>
            <h2 className="text-3xl font-bold text-slate-900 tracking-tight">
              Answering Core Architectural Inquiries
            </h2>
          </div>

          <div className="space-y-4">
            {[
              {
                q: "Where exactly is my note data stored?",
                a: "Completely inside your system's secure browser sandbox environment. You hold ultimate file ownership; your information can be fully backed up, synced manually to private assets, or compiled out clearly as clean Markdown files anytime."
              },
              {
                q: "Are there subscription walls hidden inside layout modules?",
                a: "No. Ploopus functions around an entirely entry-free baseline ecosystem. All 50+ formatting layouts, flashcard decks, kanbans, and relationship block mechanics run completely offline without paywall constraints."
              },
              {
                q: "How does the flashcard active recall engine track schedules?",
                a: "It calculates retention weight vectors entirely inside the local runtime memory thread. Progress records persist seamlessly across app boots without requiring external handshakes or third-party database logs."
              }
            ].map((faq, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-20px" }}
                transition={{ duration: 0.4, delay: index * 0.08 }}
                className="border border-slate-200/80 bg-white rounded-xl p-5 shadow-xs"
              >
                <h4 className="text-base font-bold text-slate-900 mb-2 flex items-start gap-3">
                  <span className="mt-1 shrink-0 p-0.5 rounded-md bg-slate-50 border border-slate-100 text-slate-400">
                    <Plus className="h-3 w-3" />
                  </span>
                  {faq.q}
                </h4>
                <p className="text-sm text-slate-500 leading-relaxed pl-7">{faq.a}</p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ──────────────────────────────────────────────────────── */}
        {/* PREMIUM BOTTOM CALL TO ACTION PANEL                      */}
        {/* ──────────────────────────────────────────────────────── */}
        <section className="border-t border-slate-200/70 bg-white px-4 py-20 text-center relative overflow-hidden">
          <div className="max-w-2xl mx-auto space-y-6 relative z-10">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight">
              Decouple your mind from the cloud lag.
            </h2>
            <p className="text-slate-500 max-w-md mx-auto text-sm sm:text-base leading-relaxed">
              Experience the absolute velocity of a workspace rendered instantly on native client silicon.
            </p>

            <div className="flex flex-col sm:flex-row gap-3.5 justify-center pt-4">
              <Link
                href="/"
                className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#10B981] px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#059669] transform active:scale-98 transition-all duration-150"
              >
                Start taking notes instantly
                <ArrowUpRight className="h-4 w-4" />
              </Link>
              <Link
                href="/docs"
                className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 hover:border-slate-300 transition-all duration-150"
              >
                Explore layout options
              </Link>
            </div>
          </div>
        </section>

      </div>
    </div>
  );
}